config/routes.rb
Rails.application.routes.draw do
  resources :techstacks
  resources :vacancies
  resources :main
  resources :proverka, controller: 'proverka'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'main#mp'
  get '/profile', to: 'profiles#prof'
  # get '/mp', to: 'main#mp'
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  has_rich_text :body
  belongs_to :user
  has_one :techstack, as: :entity
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: %i(show edit update destroy)

  # GET /vacancies or /vacancies.json
  def index
    @vacancies = Vacancy.all
  end

  # GET /vacancies/1 or /vacancies/1.json
  def show
  end

  # GET /vacancies/new
  def new
    @vacancy = Vacancy.new
  end

  # GET /vacancies/1/edit
  def edit
  end

  # POST /vacancies or /vacancies.json
  def create
    @vacancy = Vacancy.new(vacancy_params)

    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to @vacancy, notice: "Vacancy was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacancies/1 or /vacancies/1.json
  def update
    respond_to do |format|
      if @vacancy.update(vacancy_params)
        format.html { redirect_to @vacancy, notice: "Vacancy was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1 or /vacancies/1.json
  def destroy
    @vacancy.destroy
    respond_to do |format|
      format.html { redirect_to vacancies_url, notice: "Vacancy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vacancy
    @vacancy = Vacancy.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def vacancy_params
    params.require(:vacancy).permit(:title, :body, :term, :technical_level).merge(user: current_user)
  end
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/vacancies/_form.html.erb
<%= form_with(model: vacancy) do |form| %>
  <%= render "shared/error_messages", resource: vacancy %>

  <div class="mb-3">
    <%= form.label :title,class:'form-label' %>
    <%=form.text_field :title, class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :body,class:'form-label' %>
    <%=form.rich_text_area :body, class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :term,class:'form-label' %>
    <%=form.date_field :term, class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :technical_level,class:'form-label' %>
    <%=form.text_field :technical_level, class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Save', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/vacancies/edit.html.erb
<h1>Editing Vacancy</h1>

<%= render 'form', vacancy: @vacancy %>

<%= link_to 'Show', @vacancy %> |
<%= link_to 'Back', vacancies_path %>

app/views/vacancies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vacancies</h1>
  <tbody>
    <% @vacancies.each do |vacancy| %>
      <tr>
        <br><%=vacancy.title %><br>
        <td><%= link_to 'Show', vacancy, class: "btn btn-primary" %></td>
        <%if current_user.role != 'User' %>

        <td><%= link_to 'Edit', edit_vacancy_path(vacancy),class: "btn btn-warning" %></td>

<%if current_user.role =="Manager" %>
        <td><%= link_to 'Destroy', vacancy, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
<%end %>
      </tr>

  </tbody>
</table>

<br>
<br>
        <%end %>
  <% end %>
  <%if current_user.role == 'Manager' %>
<%= link_to 'New Vacancy', new_vacancy_path,class: "btn btn-dark" %>
  <%end %>

app/views/vacancies/new.html.erb
<h1>New Vacancy</h1>
<%= form_for :vacancy,url:vacancies_path do|f|%>

<%end %>
<%= render 'form', vacancy: @vacancy,class:"btn btn-primary" %>

<%= link_to 'Back', vacancies_path %>

app/views/vacancies/show.html.erb
<p id="notice"><%= notice %></p>
<h5>Title</h5>
<%=@vacancy.title %>
<h5> Body</h5>
<%=@vacancy.body %>
<h5>Term</h5>
<%=@vacancy.term %>
<h5>Tech_level</h5>
<%=@vacancy.technical_level %>
<h5>User_id</h5>
<%=@vacancy.user_id %>
<br>
<h5>User_email</h5>
<%=@vacancy.user.email %>
<br>
  <%if current_user.role != 'User' %>
    <%= link_to 'Edit', edit_vacancy_path(@vacancy),class: 'btn btn-warning' %>
    <%= link_to 'Add Technology stack', new_techstack_path(:entity_id => @vacancy.id, :entity_type => "Vacancy"), :class =>'btn btn-warning'  %>
    <%else %>
    <%= link_to 'Respond', root_path,class: 'btn btn-warning' %>

  <%end %>
<%=@vacancy.id %>
<%= link_to 'Show Technology stack', techstacks_path(:entity_id => @vacancy.id, :entity_type => "Vacancy"), :class =>'btn btn-warning'  %>

<%= link_to 'Back', vacancies_path , class: 'btn btn-danger'%>