config/routes.rb
Rails.application.routes.draw do
  resources :techstacks
  resources :vacancies
  resources :main
  resources :proverka, controller: 'proverka'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'main#mp'
  get '/profile', to: 'profiles#prof'
  # get '/mp', to: 'main#mp'
end

app/controllers/proverka_controller.rb
class ProverkaController < ApplicationController
  before_action :set_user, only: %i(show edit update destroy)

  def index
    @user = User.all
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to proverka_path, notice: "User was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to proverka_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:firstname, :email, :password, :password_confirmation, :lastname, :technical_level, :company_name, :status)
  end
end

app/helpers/proverka_helper.rb
module ProverkaHelper
end

app/views/proverka/_form.html.erb
<%= form_with(model: user, url: proverka_path) do |form| %>
  <%= render "shared/error_messages", resource: user %>

  <div class="field">
    <%= form.label :firstname %><br />
    <%= form.text_field :firstname, autofocus: true, class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :lastname %><br />
    <%= form.text_field :lastname, autofocus: true, class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :technical_level %><br />
    <%= form.text_field :technical_level, autofocus: true, class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :company_name %><br />
    <%= form.text_field :company_name, autofocus: true, class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :status %><br />
    <%= form.text_field :status, autofocus: true, class: 'form-control'  %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class: "form-label" %>
    <%= form.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Save', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/proverka/edit.html.erb
<h1>Editing Users </h1>

<%= render 'form', user: @user%>

<%= link_to 'Back', root_path, class:'btn btn-danger' %>

app/views/proverka/index.html.erb
<div class="container">
  <div class="row info" style="text-align:center;"></div>
<%@user.each do |usr| %>
  <div class="resume">
    <header class="page-header">
      <h1 class="page-title">Profile <%=usr.firstname%> <%=usr.lastname%></h1>
      <small> <i class="fa fa-clock-o"></i> Last Updated on: <%=usr.updated_at%> </small>
    </header>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8">
        <div class="panel panel-default">
          <div class="panel-heading resume-heading">
            <div class="row">
              <div class="col-lg-12">
                <div class="col-xs-12 col-sm-4">
                  <figure>
                    <img class="img-circle img-responsive" alt="" src="http://placehold.it/300x300">
                  </figure>
                </div>

                <div class="col-xs-12 col-sm-8">
                  <ul class="list-group">
                    <li class="list-group-item"><%=usr.firstname%> <%=usr.lastname%></li>
                    <li class="list-group-item"><%=usr.technical_level%></li>
                    <li class="list-group-item"><%=usr.company_name%> </li>
                    <li class="list-group-item"><i class="fa fa-envelope"></i> <%=usr.email%></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        <br>
        <%= link_to 'Edit profile',edit_proverka_path(usr),:class =>'btn btn-warning'  %>
        <%= link_to 'Show Technology stack', techstacks_path(:entity_id => usr.id, :entity_type => "User"), :class =>'btn btn-warning'  %>
        <%= link_to 'Add Technology stack', new_techstack_path(:entity_id => usr.id, :entity_type => "User"), :class =>'btn btn-warning'  %>
      </div>
    </div>
  </div>
</div>
<%end %>