config/routes.rb
Rails.application.routes.draw do
  resources :techstacks
  resources :vacancies
  resources :main
  resources :proverka, controller: 'proverka'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'main#mp'
  get '/profile', to: 'profiles#prof'
  # get '/mp', to: 'main#mp'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tech_stack.rb
class TechStack < ApplicationRecord
  belongs_to :entity, polymorphic: true
end

app/models/techstack.rb
class Techstack < ApplicationRecord
  belongs_to :entity, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :firstname, presence: true

  has_one :techstack, as: :entity
  has_many :vacancies
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  has_rich_text :body
  belongs_to :user
  has_one :techstack, as: :entity
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # include pundit
  before_action :authenticate_user!
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def mp
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def prof
  end
end

app/controllers/proverka_controller.rb
class ProverkaController < ApplicationController
  before_action :set_user, only: %i(show edit update destroy)

  def index
    @user = User.all
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to proverka_path, notice: "User was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to proverka_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:firstname, :email, :password, :password_confirmation, :lastname, :technical_level, :company_name, :status)
  end
end

app/controllers/techstacks_controller.rb
class TechstacksController < ApplicationController
  before_action :set_tech_stack, only: %i(show edit update destroy)

  # GET /techstacks or /techstacks.json
  def index
    @tech_stacks = Techstack.all
    @id = params[:entity_id]
    @type = params[:entity_type]
  end

  # GET /techstacks/1 or /techstacks/1.json
  def show
    @id = params[:entity_id]
  end

  # GET /techstacks/new
  def new
    @tech_stack = Techstack.new
    @tech_stack.entity_id = params[:entity_id]
    @id = params[:entity_id]
    @tech_stack.entity_type = params[:entity_type]
    if Techstack.find_by entity_id: @tech_stack.entity_id
      redirect_to techstacks_path(@id)
    end
  end

  # GET /techstacks/1/edit
  def edit
  end

  # POST /techstacks or /techstacks.json
  def create
    @tech_stack = Techstack.new(tech_stack_params)
    respond_to do |format|
      if @tech_stack.save
        format.html { redirect_to @tech_stack, notice: "Tech stack was successfully created." }
        format.json { render :show, status: :created, location: @tech_stack }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tech_stack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /techstacks/1 or /techstacks/1.json
  def update
    respond_to do |format|
      if @tech_stack.update(tech_stack_params)
        format.html { redirect_to @tech_stack, notice: "Tech stack was successfully updated." }
        format.json { render :show, status: :ok, location: @tech_stack }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tech_stack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /techstacks/1 or /techstacks/1.json
  def destroy
    @tech_stack.destroy
    respond_to do |format|
      format.html { redirect_to techstacks_url, notice: "Tech stack was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tech_stack
    @tech_stack = Techstack.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tech_stack_params
    params.require(:techstack).permit(:name, :level, :entity_id, :entity_type)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i(show edit update destroy)

  def index
    @user = User.all
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: "User was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to user_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:firstname, :email, :password, :password_confirmation, :lastname, :technical_level, :company_name, :status)
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: %i(show edit update destroy)

  # GET /vacancies or /vacancies.json
  def index
    @vacancies = Vacancy.all
  end

  # GET /vacancies/1 or /vacancies/1.json
  def show
  end

  # GET /vacancies/new
  def new
    @vacancy = Vacancy.new
  end

  # GET /vacancies/1/edit
  def edit
  end

  # POST /vacancies or /vacancies.json
  def create
    @vacancy = Vacancy.new(vacancy_params)

    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to @vacancy, notice: "Vacancy was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacancies/1 or /vacancies/1.json
  def update
    respond_to do |format|
      if @vacancy.update(vacancy_params)
        format.html { redirect_to @vacancy, notice: "Vacancy was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1 or /vacancies/1.json
  def destroy
    @vacancy.destroy
    respond_to do |format|
      format.html { redirect_to vacancies_url, notice: "Vacancy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vacancy
    @vacancy = Vacancy.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def vacancy_params
    params.require(:vacancy).permit(:title, :body, :term, :technical_level).merge(user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/proverka_helper.rb
module ProverkaHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/techstack_helper.rb
module TechstackHelper
end

app/helpers/techstacks_helper.rb
module TechstacksHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_flash_messages.html.erb
<%flash.each do |key,value|%>
  <div class="alert alert-<% key %> alert-dismissible fade show shadow-lg mb-5" role="alert">
    <%= value %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <span class="nav-link active" aria-current="page">Main page</span>
        </li>

        <li class="nav-item">
          <%=link_to"Vacancies",vacancies_path,:class=>'btn btn-warning' %>
        </li>

        <li class="nav-item">
          <%=link_to"Profile",profile_path,:class=>'btn btn-warning' %>
        </li>
        <% if current_user.role=="Admin" %>
          <a class="nav-link"> </a>
          <%= link_to 'Admin dashboard',root_path, class: 'btn btn-primary' %>
          <a class="nav-link"> </a>
        <%end %>
        <li class="nav-item">
           <%= link_to 'Log Out', destroy_user_session_path, class: 'btn btn-danger', method: :delete %>
        </li>
        <li class="nav-item">
          <a class="nav-link" style="color:darkred">Current user : <%= current_user.email %></a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recruitment Agency</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
      <main class="container py-5">
        <%render "layouts/flash_messages" %>
            <div class="row">
              <div class="mx-auto">
                <div class="card">
                  <div class="card shadow-lg ">
                    <div class="card-body p-5">
                      <%= yield %>
                    </div>
                 </div>
                </div>
              </div>
            </div>
      </main>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html class="h-100">
<head>
  <title>Recruitment Agency</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="h-100">
  <main class="container h-100">
    <div class="row h-100">
      <div class="col-md-5 mx-auto my-auto">
        <div class="card">
          <div class="card-body p-6 shadow-lg ">
            <%= render "layouts/flash_messages" %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger">
    <h4 class="alert-heading">
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
      %>
    </h4>
    <ul class="mb-0">
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>